---
version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:stable
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    networks:
      - net

  server-1:
    container_name: server-1
    image: nginx:stable
    volumes:
      - ./server-1.html:/usr/share/nginx/html/index.html:ro
    networks:
      - net

  server-2:
    container_name: server-2
    image: nginx:stable
    volumes:
      - ./server-2.html:/usr/share/nginx/html/index.html:ro
    networks:
      - net

  server-3:
    container_name: server-3
    image: nginx:stable
    volumes:
      - ./server-3.html:/usr/share/nginx/html/index.html:ro
    networks:
      - net

networks:
  net:
...
